config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.create(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten Successfully Created!"
      redirect_to kittens_url
    else
      flash.now[:danger] = "Error saving kitten"
      render 'new'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Kitten Successfully Updated!"
      redirect_to kittens_url
    else
      flash.now[:danger] = "Error updating kitten"
      render 'edit'
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:success] = "Kitten destroyed."
    redirect_to kittens_url
  end

  private

    # Never trust the scary internet!
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :age %>
		<%= f.number_field :age %>
	</p>
	<p>
		<%= f.label :cuteness %>
		<%= f.number_field :cuteness %>
	</p>
	<p>
		<%= f.label :softness %>
		<%= f.number_field :softness %>
	</p>
	<p>
		<%= f.submit "Submit" %>
	</p>
<% end %>

app/views/kittens/edit.html.erb
<h2>Edit Kitten</h2>
<%= render 'form' %>

app/views/kittens/index.html.erb
<h2>Kittens Index</h2>
<%= link_to "Create Kitten", new_kitten_path %>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Age</th>
			<th>Cuteness</th>
			<th>Softness</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @kittens.each do |kitten| %>
			<tr>
				<td><%= link_to kitten.name, kitten %></td>
				<td><%= kitten.age %></td>
				<td><%= kitten.cuteness %></td>
				<td><%= kitten.softness %></td>
				<td><%= link_to "Edit", edit_kitten_path(kitten)%> | 
						<%= link_to "Delete", kitten, method: :delete, data: { confirm: "Are you sure?" } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/kittens/new.html.erb
<h2>New Kitten</h2>
<%= render 'form' %>

app/views/kittens/show.html.erb
<h2>Kitten Details</h2>
<p>Name: <%= @kitten.name %></p>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>